package com.iql.policyadmin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CropTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropTypeAllPropertiesEquals(CropType expected, CropType actual) {
        assertCropTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCropTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropTypeAllUpdatablePropertiesEquals(CropType expected, CropType actual) {
        assertCropTypeUpdatableFieldsEquals(expected, actual);
        assertCropTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropTypeAutoGeneratedPropertiesEquals(CropType expected, CropType actual) {
        assertThat(expected)
            .as("Verify CropType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropTypeUpdatableFieldsEquals(CropType expected, CropType actual) {
        assertThat(expected)
            .as("Verify CropType relevant properties")
            .satisfies(e -> assertThat(e.getCropName()).as("check cropName").isEqualTo(actual.getCropName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropTypeUpdatableRelationshipsEquals(CropType expected, CropType actual) {
        // empty method
    }
}
