package com.iql.policyadmin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FarmAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmAllPropertiesEquals(Farm expected, Farm actual) {
        assertFarmAutoGeneratedPropertiesEquals(expected, actual);
        assertFarmAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmAllUpdatablePropertiesEquals(Farm expected, Farm actual) {
        assertFarmUpdatableFieldsEquals(expected, actual);
        assertFarmUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmAutoGeneratedPropertiesEquals(Farm expected, Farm actual) {
        assertThat(expected)
            .as("Verify Farm auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmUpdatableFieldsEquals(Farm expected, Farm actual) {
        assertThat(expected)
            .as("Verify Farm relevant properties")
            .satisfies(e -> assertThat(e.getLatitude()).as("check latitude").isEqualTo(actual.getLatitude()))
            .satisfies(e -> assertThat(e.getLongitude()).as("check longitude").isEqualTo(actual.getLongitude()))
            .satisfies(e -> assertThat(e.getCellIdentifier()).as("check cellIdentifier").isEqualTo(actual.getCellIdentifier()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmUpdatableRelationshipsEquals(Farm expected, Farm actual) {
        assertThat(expected)
            .as("Verify Farm relationships")
            .satisfies(e -> assertThat(e.getCropType()).as("check cropType").isEqualTo(actual.getCropType()))
            .satisfies(e -> assertThat(e.getFarmer()).as("check farmer").isEqualTo(actual.getFarmer()));
    }
}
