package com.iql.policyadmin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PComponentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPComponentAllPropertiesEquals(PComponent expected, PComponent actual) {
        assertPComponentAutoGeneratedPropertiesEquals(expected, actual);
        assertPComponentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPComponentAllUpdatablePropertiesEquals(PComponent expected, PComponent actual) {
        assertPComponentUpdatableFieldsEquals(expected, actual);
        assertPComponentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPComponentAutoGeneratedPropertiesEquals(PComponent expected, PComponent actual) {
        assertThat(expected)
            .as("Verify PComponent auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPComponentUpdatableFieldsEquals(PComponent expected, PComponent actual) {
        assertThat(expected)
            .as("Verify PComponent relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPComponentUpdatableRelationshipsEquals(PComponent expected, PComponent actual) {
        // empty method
    }
}
